default:
  outputs:
    dev:
      account: "{{ env_var('snowflake_account') }}"
      database: "{{ env_var('snowflake_database') }}"
      password: "{{ env_var('snowflake_password') }}"
      role: "{{ env_var('snowflake_role') }}"
      schema: "{{ env_var('snowflake_schema') }}"
      threads: 200
      type: snowflake
      user: "{{ env_var('snowflake_username') }}"
      warehouse: "{{ env_var('snowflake_warehouse') }}"
  target: dev
