default:
  outputs:
    dev:
      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      database: ${{ secrets.SNOWFLAKE_DATABASE }}
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      role: ${{ secrets.SNOWFLAKE_ROLE }}
      schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
      threads: 200
      type: snowflake
      user: ${{ secrets.SNOWFLAKE_USER }}
      warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  target: dev
